### ISSUE TITLE
Ghost-o-plasm Round Up

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#279] opened 2017-03-03 07:17 UTC
Summary - No ghosts actually spawn, no matter where you put the item.
Location - Desolace (64, 92)
Steps to Reproduce - Place Crate of Ghost Magnets down and wait. Ghosts are supposed to spawn as per http://db.vanillagaming.org/?quest=6134#comments
Screen Shots/Video - N/A
Reported By - Wreckage
Extra Information - Besthief also had encountered the same issue

post,
https://nostralia.org/forums/viewtopic.php?f=22&t=282

**Comment by pjfry651** [comment] 2017-03-03 09:02
Duplicate of #75.

**Closed by pjfry651** 2017-03-03 09:02 UTC
Labels: Priority - Low, Quest
