### ISSUE TITLE
Mobs In Silver Stream Mine Loch modan

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#115] opened 2017-01-29 09:31 UTC
Summary - Once Every now and then, Happened twice while I was clearing the mine, after agroing two mobs, i would sheep one, and kill the other. When the other mob came out of sheep it would act as if it was feard (eg running away) it would run and run and agro more mobs. EDIT * It would not run back to attack me, only keep running until it was dead!

Location - Silver Stream Mine Loch Modan 36 23

Steps to Reproduce - Agro two mobs, Sheep one, kill the other mob, then attack the mob that is a sheep.
Screen Shots/Video - N/A was too busy trying to stay alive
Reported By - demon5437
Extra Information - N/A

Forums post
http://nostralia.org/forums/viewtopic.php?f=28&t=134

**Comment by pjfry651** [comment] 2017-02-14 22:10
Duplicate of #151

**Closed by pjfry651** 2017-02-14 22:10 UTC
