### ISSUE TITLE
game quest item count is one off

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#244] opened 2017-02-19 07:49 UTC
Name - looting quest item

Summary - when you are on a quest that requires you to loot a item from a mob or possibly when your on a quest that requires you to kill a certain amount of mobs, the message that pops up saying how many you looted or killed so far is off by one saying you have picked up or killed 1 more than you already have.

example: centaur ear: 5/16      number i really have: 4/16

Location - any location, noticed it on every quest i have done that requires more than 1 item.

Steps to Reproduce - get a quest that requires looting, kill the mob and loot for item or just kill mob if the mob is only required to be killed and no quest item is needed for quest, quest needs to be more than 1 value for quest items or kills. the count should be off after looting or killing over 2 or 3 items/mobs.

Screen Shots/Video - http://s1356.photobucket.com/user/mfranca915/media/miscount_zpsjfre0ads.png

http://s1356.photobucket.com/user/mfranca915/media/miscount2_zpskirxmwyc.png.

Reported By - Koko

Extra Information - N/A

post,
http://nostralia.org/forums/posting.php?mode=edit&f=22&p=565

**Comment by natrist** [comment] 2017-03-01 19:25
Closed as duplicate of #241

**Closed by natrist** 2017-03-01 19:25 UTC
Labels: Duplicate
