### ISSUE TITLE
skinning bug

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#179] opened 2017-02-05 06:56 UTC
I have tried to train Artisan skinning from the training in Orgrimar 3 times, each time it takes 4g 50s but doesn't grant artisan skinning. I am currently 225/225 and 13g 50s down #sadface

Post,
http://nostralia.org/forums/viewtopic.php?f=23&t=180&p=380#p380

**Comment by SnowyNoS** [comment] 2017-02-05 12:23
NPC in question
http://db.vanillagaming.org/?npc=3007

More info.
You learn the skills, it takes your money but you still don't get the skill. We have removed the NPC from the game for now. The NPC works in DEVELOPMENT realm.

**Comment by natrist** [comment] 2017-02-05 17:07
We will need to reinstall the world database on the next scheduled restart and see if the bug is still present.

**Comment by natrist** [comment] 2017-02-06 05:44
I'm closing the issue as I cannot reproduce it on any internal or live region realm.

**Closed by natrist** 2017-02-06 05:44 UTC
Labels: Priority - High, System

**Comment by SnowyNoS** [comment] 2017-02-06 09:13
The player has been given the gold back by Gut.
