### ISSUE TITLE
Investigate the Blue Recluse

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#112] opened 2017-01-29 09:25 UTC
Rift Spawns do not spawn, when using Cantation of Manifestation inside the Blue Recluse tavern.

Forum post
http://nostralia.org/forums/viewtopic.php?f=22&t=112

**Comment by sundayz** [comment] 2017-01-29 12:40
Duplicate of issue #7

**Closed by sundayz** 2017-01-29 12:40 UTC
Labels: duplicate, Quest
