### ISSUE TITLE
Shaman Windfury Weapon Not Applying Extra AP

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#169] opened 2017-02-03 23:59 UTC
Hey guys, dinged 30 on my shaman Jimmy and started using windfury weapon. I noticed that the secondary attacks caused by windfury where dealing the same amount of dmg as my unbuffed attack. I did some research and found this:

https://www.reddit.com/r/Nostalrius/comments/47p24b/psa_windfury_shamans_in_general/

I know its a different server but I also believe it uses 1.12 as well so I figured I'd put this here. If it is a bug on this server too would be awesome to be fixed.

Kind regards,
stormy7712

Post,
http://nostralia.org/forums/viewtopic.php?f=29&t=163&p=345#p345

**Comment by SnowyNoS** [comment] 2017-02-05 07:01
Can we please have a look at this next, The shamans are up in arms right now....

**Comment by pjfry651** [comment] 2017-02-05 20:54
I can't reproduce this. The message for Windfury Weapon does appear after the extra attacks, but it does seem to be adding the AP as you can see from the screenshot. First attack is regular melee followed by the 2 extra attacks.

I'm not closing the issue because it's important if it's wrong, but if I could get some more information the next time someone reports this, that would help a lot in figuring out if anything is wrong.

![image](https://cloud.githubusercontent.com/assets/25411980/22629737/53ba0352-ec40-11e6-98d5-29619b9f0062.png)

**Comment by pjfry651** [comment] 2017-02-06 08:04
Going to close this after more testing and not being able to replicate. Please see forum post for more information: http://nostralia.org/forums/viewtopic.php?f=29&t=163&p=400#p400

**Closed by pjfry651** 2017-02-06 08:04 UTC
Labels: Class - Shaman, Priority - High, Spell, System
