### ISSUE TITLE
Shield Bash

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#120] opened 2017-01-29 09:40 UTC
Shield Bash doesnt interupt spells. only tested in pve. i can test in pvp soon.

Forum post.
http://nostralia.org/forums/viewtopic.php?f=14&t=88

**Comment by sundayz** [comment] 2017-02-04 02:55
Duplicate of #46.

**Closed by sundayz** 2017-02-04 02:55 UTC
Labels: Invalid/Won't Fix, Spell
