### ISSUE TITLE
Level 15 Mage Quest

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#134] opened 2017-01-29 10:26 UTC
The level 15 mage quest item cantation of manifestation is supposed to spawn mobs, however none are spawning when the item is being used.

I am submitting this on behalf of someone else with the issue, they have noted that they have looked this up on youtube and confirmed it is bugged

Post
http://nostralia.org/forums/posting.php?mode=edit&f=22&p=254

**Comment by sundayz** [comment] 2017-01-29 12:42
Duplicate of issue #7

**Closed by sundayz** 2017-01-29 12:42 UTC
Labels: duplicate, Quest
