### ISSUE TITLE
Zul'farrak event

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#289] opened 2017-03-03 07:33 UTC
Name - event after the stairs part, to engage the prisoners and have the goblin destroy the wall to allow access to final boss. 
Summary - after finishing the stairs event and boss there I attempted to talk to goblin dude to get him to blow the wall, allowing access up to the final boss. He would only greet me, nothing more. Additionally the other NPC's all hearthstoned out about 5-10 seconds later without us having the chance to fight them for the quest
Steps to Reproduce - complete stairs event, wait for them to hearth, talk to goblin.
Screen Shots/Video - 
Reported By paprika
Extra Information - I believe the npcs hearthing away may have been due to the group being half horde half alliance. From memory only horde fight them for a quest, alliance don't.

post,
https://nostralia.org/forums/viewtopic.php?f=24&t=274

**Comment by pjfry651** [comment] 2017-03-03 09:05
Duplicate of #255

**Closed by pjfry651** 2017-03-03 09:05 UTC
Labels: Dungeon, Priority - Medium, System
