### ISSUE TITLE
Uncovering the Past

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#163] opened 2017-02-03 07:28 UTC
This quest is to find 4 fragments by looting each of them on the ground. The Neru Fragment is nowhere to be found. Having done this on live many moons ago I know this quest well enough.

Post,
http://nostralia.org/forums/viewtopic.php?f=22&t=111&p=344#p344

**Comment by sundayz** [comment] 2017-02-03 09:04
Duplicate of #113.

**Closed by sundayz** 2017-02-03 09:04 UTC
Labels: Duplicate, Quest
