### ISSUE TITLE
Wailing Caverns - Mutanus the Devourer Despawn

### ISSUE THREAD

**Issue by Gutr0t** [NostraliaWoW/mangoszero#15] opened 2017-01-29 05:15 UTC
Mutanus the Devourer's (this NPC is spawned by a script) respawn timer is at 25 seconds, so he disapears in the middle of people rolling for loot [wailing caverns]

**Comment by sundayz** [comment] 2017-01-29 20:24
Fixed in fb0265c.

Tried doing it through SD3, but SetRespawnTime kept causing an error.

**Comment by Nostralia** [comment] 2017-02-01 07:47
Tested, the issue is still there as described initially (possibly just increase respawn time)

**Comment by Nostralia** [comment] 2017-02-01 09:04
Still doesn't work after correct lua folder contests set. We checked npc info, said 10 hour respawn time, yet he still despawned which affected loot share afterwards

**Closed** 2017-02-01 09:59 UTC
Labels: bug, Dungeon, NPC
