### ISSUE TITLE
A Final Blow - Mind Control

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#307] opened 2017-03-08 10:50 UTC
Name - A Final Blow
Summary - Shadow Lord Fel'dan's Mind Control resets combat aggro, no diminishing return
Location - http://db.vanillagaming.org/?quest=5242#wh-comments
Steps to Reproduce - Attacked the three mobs, mind controlled upon combat start, mobs reset.
Screen Shots/Video - Whitnessed Gronk attempting to kill mob, managed to get 1-2 attacks off than mind controlled mobs health reset due to out of combat.
Reported By - Gronk - 7/03/17
Extra Information - N/A

post,
https://nostralia.org/forums/viewtopic.php?f=22&t=345

**Comment by mfranca0009** [comment] 2017-03-08 14:43
This is a duplicate of what is happening with #300.

**Closed** 2017-03-08 14:51 UTC
Labels: Duplicate
