### ISSUE TITLE
Blacksmithing: Choose Your Fate Bug

### ISSUE THREAD

**Issue by mfranca0009** [NostraliaWoW/mangoszero#299] opened 2017-03-06 04:22 UTC
Will not let you choose being a armorsmith or weaponsmith, if you click on either of the options it does nothing. 

NPC: Myolor Sunderfury

Location: Ironforge

Reproduce: Believe you should have 150 skill for blacksmithing or more then speak to Myolor Sunderfury to choose being a armorsmith or weaponsmith.

**Comment by SnowyNoS** [comment] 2017-03-06 07:43
Please close this as its working as intended.

**Closed** 2017-03-06 08:08 UTC
Labels: Invalid/Won't Fix, NPC, Priority - Low
